# Домашнее задание к лекции "Библиотека NumPY, вычислительные задачи"

### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [67]:
import numpy as np   # импортируем библиотеку высокоуровневых математических функций для операций с массивами

N = 10                # задаем переменную N
a = np.arange(0, N)  # с помощью функции arange() создадим массив, содержащий арифметическую прогрессию от 0 до N
b = np.flip(a)       # с помощью функции flip() расположим числа в обратном порядке
b

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [68]:
c = np.diag(b) # с помощью функции diag() построим диагональную матрицу из одномерного массива b из задания 1
print(c)
np.trace(c)    # функция trace() вычисляет cумму диагональных элементов матрицы

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


45

### Задание 3

Решите систему уравнений:
- 4x + 2y + z = 4
- x + 3y = 12
- 5y + 4z = -3

In [69]:
M = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]]) # Матрица - левая часть системы
# print(M)
v = np.array([4, 12, -3])                       # Вектор - правая часть системы
# print(v)
x = np.linalg.solve(M, v)                       # Для решения системы воспользуемся функцией numpy.linalg.solve модуля numpy
# x
print(f'Ответ: x = {x[0]}, y = {x[1]}, z = {x[2]}')

Ответ: x = 0.4666666666666668, y = 3.844444444444444, z = -5.555555555555555


### Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [40]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

users_stats[0]

array([2, 1, 0, 0, 0, 0])

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [36]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [72]:
def cosine(a):
    """
    Подсчет косинуса угла между векторами (в нашем случае, элементы массива users_stats[a] и вектор next_user_stats) по их координатам
    """
    # длины векторов с помощью функции linalg.norm()
    aLength = np.linalg.norm( users_stats[a] )
    bLength = np.linalg.norm( next_user_stats )
    
    # отношение произведения векторов (скалярное произведение считаем с помощью функции dot()) к произведению длин векторов
    rez = np.dot( users_stats[a], next_user_stats ) / ( aLength * bLength ) 
    
    # выводить будем самый близкий к 1 результат
    if rez > 0.9:
        print(f'Найден самый похожий пользователь: User ID {a + 1}')
        print(f'Косинусное сходство = {rez}')

In [73]:
cosine(0)
cosine(1)
cosine(2)
cosine(3)
cosine(4)
cosine(5)
cosine(6)
cosine(7)
cosine(8)
cosine(9)

Найден самый похожий пользователь: User ID 8
Косинусное сходство = 0.9486832980505138
